
name: Set bucket environment variables
description: | 
  Sets KERNEL_PACKAGE_BUCKET and KERNEL_BUNDLE_BUCKET based on
  the branch.
runs:
  using: composite
  env:
    BUILD_ID: "${{ github.run_id }}"
    KERNEL_PACKAGE_BUCKET: "gs://stackrox-kernel-packages-staging/copy"
    KERNEL_BUNDLE_BUCKET: "gs://collector-kernel-bundles-public"
    KERNEL_PACKAGE_STAGING_BUCKET: ":gs://stackrox-kernel-packages-staging"
    KERNEL_BUNDLE_STAGING_BUCKET: "gs://stackrox-kernel-bundles-staging"
  steps:
    - run: |
        if [[ "${{ github.ref }}" =~ (master|main)$ ]]; then
          echo "Using production buckets"
        else
          echo "Using staging buckets"
          KERNEL_PACKAGE_BUCKET="${KERNEL_PACKAGE_STAGING_BUCKET},${KERNEL_PACKAGE_BUCKET}"
          KERNEL_BUNDLE_BUCKET="${KERNEL_BUNDLE_STAGING_BUCKET},${KERNEL_BUNDLE_BUCKET}"
        fi

        echo "KERNEL_PACKAGE_BUCKET=${KERNEL_PACKAGE_BUCKET}" | tee -s "$GITHUB_ENV"
        echo "KERNEL_BUNDLE_BUCKET=${KERNEL_BUNDLE_BUCKET}" | tee -s "$GITHUB_ENV"

