name: Set bucket environment variables
description: | 
  Sets common environment variables and gets GCP secrets for use
  during other stages.
runs:
  using: composite
  steps:
    - run: |
        if [[ "${{ github.ref }}" =~ (master|main)$ ]]; then
          echo "Using production buckets"
        else
          echo "Using staging buckets"
          KERNEL_PACKAGE_BUCKET="${KERNEL_PACKAGE_STAGING_BUCKET},${KERNEL_PACKAGE_BUCKET}"
          KERNEL_BUNDLE_BUCKET="${KERNEL_BUNDLE_STAGING_BUCKET},${KERNEL_BUNDLE_BUCKET}"
        fi

        echo "KERNEL_PACKAGE_BUCKET=${KERNEL_PACKAGE_BUCKET}" | tee -a "$GITHUB_ENV"
        echo "KERNEL_BUNDLE_BUCKET=${KERNEL_BUNDLE_BUCKET}" | tee -a "$GITHUB_ENV"
        echo "BUILD_ID=${BUILD_ID}" | tee -a "$GITHUB_ENV"
      shell: bash
      env:
        BUILD_ID: "${{ github.run_id }}"
        KERNEL_PACKAGE_BUCKET: "gs://stackrox-kernel-packages-staging/copy"
        KERNEL_BUNDLE_BUCKET: "gs://collector-kernel-bundles-public"
        KERNEL_PACKAGE_STAGING_BUCKET: "gs://stackrox-kernel-packages-staging"
        KERNEL_BUNDLE_STAGING_BUCKET: "gs://stackrox-kernel-bundles-staging"

    - uses: google-github-actions/get-secretmanager-secrets@v1
      id: get-secrets
      with:
        secrets: |
          rhel:stackrox-ci/collector-kernel-crawler-rhel-credentials
          ubuntu:stackrox-ci/collector-kernel-crawler-ubuntu-credentials

      #suse:stackrox-ci/collector-kernel-crawler-suse-credentials
    - run: |
        import os

        # mutli-line strings because possibility of multi-line secrets
        rhel = """${{ steps.get-secrets.outputs.rhel }}\n"""
        ubuntu = """${{ steps.get-secrets.outputs.suse }}\n"""
        suse = """${{ steps.get-secrets.outputs.ubuntu }}\n"""

        masks = []

        for line in filter(None, (rhel + ubuntu + suse).splitlines()):
          _, value = line.split('=', 1)
          print(f'::add-mask::{value}')

        with open(os.environ['GITHUB_ENV'], 'w') as env:
          env.write(rhel)
          env.write(ubuntu)
          env.write(suse)

      shell: python
