name: Set bucket environment variables
description: | 
  Sets common environment variables and gets GCP secrets for use
  during other stages.
runs:
  using: composite
  env:
    BUILD_ID: "${{ github.run_id }}"
    KERNEL_PACKAGE_BUCKET: "gs://stackrox-kernel-packages-staging/copy"
    KERNEL_BUNDLE_BUCKET: "gs://collector-kernel-bundles-public"
    KERNEL_PACKAGE_STAGING_BUCKET: "gs://stackrox-kernel-packages-staging"
    KERNEL_BUNDLE_STAGING_BUCKET: "gs://stackrox-kernel-bundles-staging"
  steps:
    - if: github.event_name == 'schedule'
      run: |
        # TODO: remove these three lines when transitioning completely
        #       away from OSCI
        echo "Using staging buckets"
        KERNEL_PACKAGE_BUCKET="${KERNEL_PACKAGE_STAGING_BUCKET},${KERNEL_PACKAGE_BUCKET}"
        KERNEL_BUNDLE_BUCKET="${KERNEL_BUNDLE_STAGING_BUCKET},${KERNEL_BUNDLE_BUCKET}"

        echo "KERNEL_PACKAGE_BUCKET=${KERNEL_PACKAGE_BUCKET}" | tee -a "$GITHUB_ENV"
        echo "KERNEL_BUNDLE_BUCKET=${KERNEL_BUNDLE_BUCKET}" | tee -a "$GITHUB_ENV"
        echo "BUILD_ID=${BUILD_ID}" | tee -a "$GITHUB_ENV"
      shell: bash

    - if: github.event_name == 'pull_request'
      run: |
        echo "Using staging buckets"
        KERNEL_PACKAGE_BUCKET="${KERNEL_PACKAGE_STAGING_BUCKET},${KERNEL_PACKAGE_BUCKET}"
        KERNEL_BUNDLE_BUCKET="${KERNEL_BUNDLE_STAGING_BUCKET},${KERNEL_BUNDLE_BUCKET}"

        echo "KERNEL_PACKAGE_BUCKET=${KERNEL_PACKAGE_BUCKET}" | tee -a "$GITHUB_ENV"
        echo "KERNEL_BUNDLE_BUCKET=${KERNEL_BUNDLE_BUCKET}" | tee -a "$GITHUB_ENV"
        echo "BUILD_ID=${BUILD_ID}" | tee -a "$GITHUB_ENV"
