FROM registry.redhat.io/rhel7/rhel:7.7
# https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhel7/rhel

COPY entrypoint /usr/bin/entrypoint

ENTRYPOINT ["/usr/bin/entrypoint"]
