repos:
  - repo: https://github.com/syntaqx/git-hooks.git
    rev: "v0.0.17"
    hooks:
      - id: shfmt
        args:
          - -d
      - id: shellcheck

  - repo: https://github.com/pycqa/flake8.git
    rev: "4.0.1"
    hooks:
      - id: flake8

  - repo: https://github.com/rhysd/actionlint.git
    rev: "v1.6.22"
    hooks:
      - id: actionlint-docker
