[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "joshdk/consistent-map-key-sorting"
  source = "https://github.com/joshdk/yaml.git"

[prune]
  go-tests = true
  unused-packages = true
