#!/bin/sh
set -eu

main() {
    CRAWLED_PACKAGE_DIR="${1:-kernel-package-lists}"

    # Check if there are actually any changes. If no files have been modified,
    # don't bother committing.
    if git diff-index --quiet HEAD -- "$CRAWLED_PACKAGE_DIR"; then
        echo "Crawled packages are up to date. Stopping build."
        return 0
    fi

    # Create a commit with any modified files, and push it to GitHub on a
    # special branch.
    git checkout -B roxbot/crawl
    git add "$CRAWLED_PACKAGE_DIR"
    git -c "user.name=roxbot" -c "user.email=roxbot@stackrox.com" commit --message "🤖 Updated crawled packages"
    git push origin roxbot/crawl --force
    echo "Crawled packages have been pushed. Please open a pull request."
    echo "Visit https://github.com/stackrox/kernel-packer/pull/new/roxbot/crawl"
}

main "$@"
