name: Repackage
description: Runs the kernel-packer repackage step
runs:
  using: composite
  steps:
    - name: prepare cache
      run: |
        if [ ! -f .build-data/cache/cache.yml ]; then
          IFS=',' read -r -a bucket_names <<< "${KERNEL_BUNDLE_BUCKET}"
          for bucket in "${bucket_names[@]}"
            do
              gsutil cp "${bucket}/cache.yml" .build-data/cache/cache.yml || true
            fi
          done
        fi
        touch .build-data/cache/cache.yml
      shell: bash
    
    - name: List Files
      run: make list-files
      shell: bash

    - name: Archive package list
      uses: actions/upload-artifact@v3
      with:
        name: package-list
        path: .build-data/packages.txt

    - name: Download packages
      run: make download-packages packers
      shell: bash

    - name: Repackage
      run: make repackage
      shell: bash

    - name: Upload bundles
      run: make upload-bundles
      shell: bash
