#! /bin/bash

# 1. check that we have jq and yq
# 2. check that filter query exists in existing manifest
# 3. create tempoary manifest and build

DIR="$(cd "$(dirname "$0")" && pwd)"
set -e

tmp_manifest="$(mktemp)"
yq r -j "${DIR}/../kernel-package-lists/manifest.yml" | jq 'to_entries[] | select(.value.packages[] | contains("'"$1"'")) | [.] | from_entries' | jq -s add | yq r -P - > "${tmp_manifest}"

echo "Filtered manifest ${tmp_manifest}"
cat "${tmp_manifest}"

MANIFEST_FILE="${tmp_manifest}" make -C "${DIR}/.." bundles

rm -f "${tmp_manifest}"
