#!/usr/bin/env bash

main() {
    # GCS bucket containing uploaded files.
    #
    # Example: "gs://stackrox-kernel-packages"
    bucket_names=("$@")
    if [[ "${#bucket_names[@]}" == 0 ]]; then
      bucket_names=(gs://stackrox-kernel-packages)
    fi

    for bucket_name in "${bucket_names[@]}"; do
      if [[ "$bucket_name" == gs://* ]]; then
        gsutil --quiet ls "$bucket_name"
      else
        find "$bucket_name" -type f -maxdepth 1
      fi
    done | strip_bucket_prefix | sort | uniq
}

strip_bucket_prefix() {
    sed 's|.*/||'
}

main "$@"
