#!/usr/bin/env bash

main() {
    # GCS bucket(s) containing uploaded files.
    #
    # Example: "gs://stackrox-kernel-packages"
    bucket_name_list="${1:-gs://stackrox-kernel-packages}"

    IFS=',' read -r -a bucket_names <<< "$bucket_name_list"
    for bucket_name in "${bucket_names[@]}"; do
      gsutil --quiet ls "$bucket_name"
    done | strip_bucket_prefix | sort
}

strip_bucket_prefix() {
    sed 's|.*/||'
}

main "$@"
