#!/usr/bin/env bash
set -eu

ROBOT_ROX_GITHUB_TOKEN="${ROBOT_ROX_GITHUB_TOKEN:-$GITHUB_TOKEN}"

main() {
    CRAWLED_PACKAGE_DIR="${1:-kernel-package-lists}"
    BRANCH=$(git rev-parse --abbrev-ref HEAD)

    refresh_repo .

    # Check if there are actually any changes. If no files have been modified,
    # don't bother committing.
    if git diff-index --quiet HEAD -- "$CRAWLED_PACKAGE_DIR"; then
        echo "Crawled packages are up to date. Stopping build."
        return 0
    fi

    echo "New crawled packages found!"

    # At the moment there is no remote git repository set, we have to configure
    # it first. Redirect to devnull so this doesn't print the value of the
    # token on failure.
    echo "Add target..."
    git remote add pushtarget https://roxbot:$ROBOT_ROX_GITHUB_TOKEN@github.com/stackrox/kernel-packer &> /dev/null

    # Create a commit with any modified files, and push it to GitHub.
    echo "Commit changes..."
    git add "$CRAWLED_PACKAGE_DIR"
    git -c "user.name=roxbot" -c "user.email=roxbot@stackrox.com" commit --message "🤖 Updated crawled packages"

    # redirect to devnull so this doesn't print the value of the token on failure.
    # temporary test branch
    echo "Push changes..."
    git push pushtarget $BRANCH
    echo "Crawled packages have been pushed."
}

refresh_repo() {
    repo_dir="$1"

    git -C "$repo_dir" update-index -q --refresh 1>/dev/null 2>&1 || true
}

main "$@"
