#!/bin/sh
set -eu

main() {
    CRAWLED_PACKAGE_DIR="${1:-kernel-package-lists}"

    refresh_repo .

    # Check if there are actually any changes. If no files have been modified,
    # don't bother committing.
    if git diff-index --quiet HEAD -- "$CRAWLED_PACKAGE_DIR"; then
        echo "Crawled packages are up to date. Stopping build."
        return 0
    fi

    echo "New crawled packages found!"

    # Create a commit with any modified files, and push it to GitHub.
    git add "$CRAWLED_PACKAGE_DIR"
    git -c "user.name=roxbot" -c "user.email=roxbot@stackrox.com" commit --message "🤖 Updated crawled packages"
    git push origin
    echo "Crawled packages have been pushed."
}

refresh_repo() {
    repo_dir="$1"

    git -C "$repo_dir" update-index -q --refresh 1>/dev/null 2>&1 || true
}

main "$@"
