#!/usr/bin/env bash

DIR="$(cd "$(dirname "$0")" && pwd)"

info() {
    echo "[INFO] $*" 1>&2
}

main() {
    # Directory that holds the crawled url text files.
    #
    # Example: "./kernel-package-lists"
    package_list_dir="$1"

    # GCS bucket containing uploaded files.
    #
    # Example: "gs://stackrox-kernel-packages"
    bucket_name_list="$2"
    IFS=',' read -r -a bucket_names <<< "$bucket_name_list"

    # Directory to download urls into.
    #
    # Example: ".build-data/downloads"
    download_dir="$3"
    mkdir -p "$download_dir"

    info 'Generating a list of crawled urls.'
    all_crawled_packages="$(./scripts/crawled-inventory "$package_list_dir")"
    echo "$all_crawled_packages"
    echo

    info 'Generating a list of bucket files.'
    all_bucket_files="$(./scripts/package-inventory "$bucket_name_list")"
    echo "$all_bucket_files"
    echo

    info 'Downloading missing files from origin source.'
    while read -r url; do
        # Simplify url into the naming scheme used in the bucket.
        filename="$(simplify "$url")"

        # Check if this specific file exists in the bucket listing.
        if ! echo "$all_bucket_files" | contains_exact "$filename"; then
            echo "Downloading $url"

            # This file didn't exist in the bucket listing, so download it.
            download "$url" "${download_dir}/${filename}"
        fi
    done <<< "$all_crawled_packages"
    echo

    info 'Sanity checking downloaded files.'
    find "${download_dir}" -size 0 -delete -print
    echo

    info "Uploading files to ${bucket_names[0]}/"
    find "$download_dir" -type f | gsutil -m cp -I "${bucket_names[0]%/}/"
    echo
}

contains_exact() {
    grep -Eq ^"$1"$
}

contains() {
    grep -qF "$1"
}

get_rhsm_api_access_token() {
    token_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    curl $token_url -d grant_type=refresh_token -d client_id=rhsm-api -d refresh_token=$RHSM_OFFLINE_TOKEN | jq '.access_token' | tr -d '"'
}

download_using_rhsm_api() {
	url=$1
	file=$2

	url=$(echo $url | tr -d '\r')

	token="$(get_rhsm_api_access_token)"
	url_info="$(curl -H "Authorization: Bearer $token" "$url" -H "accept: application/json")"
	temp_url="$(echo $url_info | jq -r .body.href)"
	curl -H "Authorization: Bearer $token" "$temp_url" --output "$file" || rm -f "$file"
}

download() {
    url="$1"
    file="$2"
    if echo "$url" | contains 'cdn.redhat.com'; then
        wget \
            --no-check-certificate \
            --certificate .build-data/rhel-certs/rhel-cert.pem \
            --private-key .build-data/rhel-certs/rhel-key.pem \
            -nv "$url" -O "$file" || rm -f "$file"
    elif echo "$url" | contains 'api.access.redhat.com'; then
	download_using_rhsm_api "$url" "$file"
    elif echo "$url" | contains 'docker.io'; then
        wget \
            --header "$("${DIR}/docker-desktop/auth-header.sh")" \
            -nv "$url" -O "$file" || rm -f "$file"
    elif echo "$url" | contains 'updates.suse.com'; then
        base_url="$(echo "$url" | rev | cut -d'/' -f3- | rev)/"
        tokens_file="${DIR}/../.build-data/suse-repo-tokens/repos.json"
        token="$(jq -r --arg BASE_URL "${base_url}" '.[]|select(.url|contains($BASE_URL))|.token' "${tokens_file}")"
        wget -nv "${url}?${token}" -O "$file" || rm -f "$file"
    elif echo "$url" | contains 'esm.ubuntu.com/infra/'; then
        wget -nv --user "bearer" --password "$UBUNTU_ESM_INFRA_BEARER_TOKEN" "$url" -O "$file" || rm -f "$file"
    elif echo "$url" | contains 'esm.ubuntu.com/fips/'; then
        wget -nv --user "bearer" --password "$UBUNTU_FIPS_BEARER_TOKEN" "$url" -O "$file" || rm -f "$file"
    elif echo "$url" | contains 'esm.ubuntu.com/fips-updates/'; then
        wget -nv --user "bearer" --password "$UBUNTU_FIPS_UPDATES_BEARER_TOKEN" "$url" -O "$file" || rm -f "$file"
    else
        wget -nv "$url" -O "$file" || rm -f "$file"
    fi
}

simplify() {
    echo "$1" | tr -c 'a-zA-Z0-9_.\n' '-'
}

main "$@"
