#!/usr/bin/env bash

# Retrieve and print the fips bearer token, based on https://github.com/canonical/ubuntu-advantage-client.

set -euo pipefail

if [[ -z "$UBUNTU_FIPS_SUBSCRIPTION_TOKEN" ]]; then
    echo "Environment variable 'UBUNTU_FIPS_SUBSCRIPTION_TOKEN' is undefined" 1>&2
    exit 1
fi

UBUNTU_FIPS_ATTACH_URL="${UBUNTU_FIPS_ATTACH_URL:-https://contracts.canonical.com/v1/resources/fips/context/machines/930f3ea7ac23ddc47f14216b9249d216}"

# Attach fake machine and extract esm-infra bearer token used to access esm apt repositories.
repo_esm_token="$(curl -kfs \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: Bearer ${UBUNTU_FIPS_SUBSCRIPTION_TOKEN}" \
  "${UBUNTU_FIPS_ATTACH_URL}" | jq -r '.resourceToken')"

echo "${repo_esm_token}"
