#!/usr/bin/env bash

info() {
    echo "[INFO] $*" 1>&2
}

main() {
    # GCS bucket containing uploaded files.
    #
    # Example: "gs://stackrox-kernel-packages"
    bucket_name="$1"

    # Directory in which downloaded urls are stored.
    #
    # Example: ".build-data/downloads"
    download_dir="$2"

    info 'Sanity checking downloaded files.'
    find "${download_dir}" -size 0 -delete -print
    echo

    info 'Uploading files to bucket.'
    find "$download_dir" -type f | gsutil -m cp -I "$bucket_name"
    echo
}

main "$@"
