name: Import GCP credentials
description: Imports crawling credentials from GCP
inputs:
  gcp-auth:
    description: The JSON credentials to use to auth with GCP
    required: true
runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ inputs.gcp-auth }}'

    - uses: google-github-actions/get-secretmanager-secrets@v1
      id: get-secrets
      with:
        secrets: |
          rhel:stackrox-ci/collector-kernel-crawler-rhel-credentials
          ubuntu:stackrox-ci/collector-kernel-crawler-ubuntu-credentials

      #suse:stackrox-ci/collector-kernel-crawler-suse-credentials
    - run: |
        echo "${{ steps.get-secrets.outputs.rhel }}" >> $GITHUB_ENV
        echo "${{ steps.get-secrets.outputs.suse }}" >> $GITHUB_ENV
        echo "${{ steps.get-secrets.outputs.ubuntu }}" >> $GITHUB_ENV
      shell: bash
