name: Format comment for crawling PR
description: |
  Format a GitHub comment to be added to a PR, stating number of
  packages and bundles, alongside the buckets used for staging.
inputs:
  package-bucket:
    description: Staging bucket for packages
    required: true
  bundle-bucket:
    description: Staging bucket for bundles
    required: true
  credentials:
    description: Credentials needed to list the buckets
    required: true

outputs:
  comment:
    description: The comment to posted on the PR
    value: ${{ steps.formatted-comment.outputs.comment }}

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ inputs.credentials }}'
    - uses: google-github-actions/setup-gcloud@v1

    - shell: bash
      id: formatted-comment
      env:
        KERNEL_PACKAGE_STAGING_BUCKET: ${{ inputs.package-bucket }}
        KERNEL_BUNDLE_STAGING_BUCKET: ${{ inputs.bundle-bucket }}
      run: |
        export PACKAGE_COUNT="$(gsutil ls "${KERNEL_PACKAGE_STAGING_BUCKET}" | wc -l | xargs)"
        export BUNDLE_COUNT="$(gsutil ls "${KERNEL_BUNDLE_STAGING_BUCKET}" | wc -l | xargs)"
        export LAST_UPDATED="$(date)"

        formatted_comment="$(mktemp)"

        envsubst < ${{ github.action_path }}/comment.md > "${formatted_comment}"
        echo "comment=\"$(cat "${formatted_comment}")\"" >> "${GITHUB_OUTPUT}"
