name: Cache

on:
  workflow_call:


jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT }}'
      - uses: google-github-actions/setup-gcloud@v1
        
      - uses: ./.github/actions/env

      - name: Combine cache
        run: make combine-cache

      - name: Clean cache
        run: make clean-cache

      - name: Sanity check bundles
        run: |
          IFS=',' read -r -a bucket_names <<< "${KERNEL_BUNDLE_BUCKET}"
          for bucket_name in "${bucket_names[@]}"; do
            echo "Kernel versions in ${bucket_name}"
            gsutil ls "${bucket_name}/**.tgz" | \
              sed 's|^.*bundle-||' | sed 's|\.tgz$||' | sort || true
          done

          gsutil cp .build-data/cache/cache.yml "${bucket_names[0]}/cache.yml"
