name: Crawler

on:
  #schedule:
  #  - cron: '15 */8 * * *'
  pull_request:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/env
      - uses: ./.github/actions/gcp-creds
        with:
          gcp-auth: '${{ secrets.GOOGLE_CREDENTIALS_KERNEL_CACHE }}'

      - name: Run crawl
        env:
          REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
          RHSM_OFFLINE_TOKEN: ${{ secrets.RHSM_OFFLINE_TOKEN }}
        run: |
          if ! make -k crawl 2> >(tee /tmp/make-crawl-stderr >&2) ; then
              touch /tmp/crawl-failed
          fi

          if [[ -f /tmp/crawl-failed ]] || grep -Eq '\*\*\* \[[a-zA-Z0-9-]+\] Error' /tmp/make-crawl-stderr ; then
              echo >&2 "'make crawl' failed. See the output of the 'Crawl package repositories' step in the crawl job for further details."
              exit 1
          fi

          ./scripts/restore-removed

      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: kernel-crawler-log
          path: kernel-crawler/kernel-crawler.log


