name: Kernel Packer

on:
  pull_request:
  schedule:
    - cron: '15 */2 * * *'

permissions:
  pull-requests: write

jobs:
  crawl:
    uses: ./.github/workflows/crawl.yml
    secrets: inherit

  repackage:
    uses: ./.github/workflows/repackage.yml
    needs: crawl
    secrets: inherit

  comment-on-pr:
    uses: ./.github/workflows/pr-comment.yml
    if: github.event_name == 'pull_request'
    needs:
    - crawl
    - repackage
    secrets: inherit
    with:
      uploaded-packages: ${{ needs.crawl.outputs.uploaded-packages }}
      uploaded-bundles: ${{ needs.repackage.outputs.uploaded-bundles }}

  check-errors:
    needs: crawl
    runs-on: ubuntu-latest
    steps:
    - name: Restore files
      uses: actions/download-artifact@v3
      with:
        name: kernel-crawler-errors
        path: /tmp/

    - name: Check errors
      run: |
        if [[ -f /tmp/crawl-failed ]] || grep -Eq '\*\*\* \[[:[:space:]a-zA-Z0-9-]+\] Error' /tmp/make-crawl-stderr ; then
            echo >&2 "'make crawl' failed."
            exit 1
        fi

    - name: Slack notification
      if: failure() && github.event_name == 'schedule'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_COLLECTOR_ONCALL_WEBHOOK }}
        SLACK_CHANNEL: team-acs-collector-oncall
        SLACK_COLOR: ${{ job.status }}
        SLACK_LINK_NAMES: true
        SLACK_TITLE: Kernel Crawling Failed
        MSG_MINIMAL: actions url,commit
        SLACK_MESSAGE: |
          @acs-collector-team
