name: Kernel Packer

on:
  pull_request:
  schedule:
    - cron: '15 */2 * * *'

jobs:
  crawl:
    if: contains(github.event.pull_request.labels.*.name, 'crawl')
    uses: ./.github/workflows/crawl.yml
    secrets: inherit

  repackage:
    uses: ./.github/workflows/repackage.yml
    needs: crawl
    secrets: inherit

