name: Kernel Packer

on:
  pull_request:
  schedule:
    - cron: '15 */8 * * *'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_KERNEL_CACHE }}'

      - uses: google-github-actions/setup-gcloud@v1

      - uses: ./.github/actions/env

      #
      # Each step of the crawl/repackage process is a composite
      # action because we need to run everything in a single job
      # to maintain repository state between each step
      #
      - name: Crawl
        uses: ./.github/actions/crawl

      - name: Sync
        uses: ./.github/actions/sync

      - name: Repackage
        uses: ./.github/actions/repackage

      - name: Cache
        uses: ./.github/actions/cache

      - name: Commit to Collector Repo
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          make robo-collector-commit


