name: Repackage Bundles

on: workflow_call

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/env

      - uses: ./.github/actions/crawl-comment
        id: comment
        with:
          package-buckets: ${{ env.KERNEL_PACKAGE_BUCKET }}
          bundle-buckets: ${{ env.KERNEL_BUNDLE_BUCKET }}
          credentials: ${{ secrets.GOOGLE_CREDENTIALS_KERNEL_CACHE }}

      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ${{ steps.comment.outputs.comment }}
          message-id: crawl-results

